FROM ubuntu:20.04

LABEL mainteiner = "Salvador HM salvadorhm@gmail.com"
LABEL version = "V0.1"
LABEL description = "Ubuntu 20.04, PHP7.4.3 and SQLite3"

RUN apt-get update

RUN apt-get install -y php-fpm
RUN apt-get install -y php-sqlite3 
RUN apt-get install -y sqlite3